name: Deployment

on:
  push:
    branches: [ "master" ]
    tags:
      - '/^v\d+\.\d+\.\d+/'

env:
  CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_TOKEN }}

jobs:
  publish:
    name: Deploy-crate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: dry-run
        run: cargo publish --dry-run
      - name: publish
        run: cargo publish
      
