name: Deployment

on:
  push:
    tags: [ "v*" ]

env:
  CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_TOKEN }}

jobs:
  Deploy:
    name: Deploy-Crate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: bump-cargo-version
        run: |
          export VERSION=${{ github.event.release.tag_name }}
          sed -i "s/0.0.0/$VERSION/g" Cargo.toml
      - name: dry-run
        run: cargo publish --dry-run --allow-dirty
      - name: publish
        run: cargo publish
